### PR TITLE
Add gap/column-gap/row-gap classes

### PR DESCRIPTION
**Pull request by dchenk**
Supported by all modern browsers, the `gap`, `column-gap`, and `row-gap` CSS properties are extremely useful, especially with flexbox: https://developer.mozilla.org/en-US/docs/Web/CSS/gap

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by dchenk** [comment]
Thanks for the approval @melloware — will we see this merged soon?

**Comment by melloware** [comment]
@dchenk I don't work for PrimeTek I am just an open source committer so its up to @cagataycivici or anyone from PrimeTek to merge it.

**Comment by melloware** [comment]
Looks like @mertsincan just added this feature in master with his latest commit can you check it out ?

**Comment by mertsincan** [comment]
Hi @dchenk,

So sorry, I haven't seen your PR :(

**Pull request closed without merging**
