### PR TITLE
Hide Classes - Responsive

### PR DESCRIPTION
**Pull request by praveenkumar-outlook**
Added classes to hide elements for mobile responsive.
Some elements need to be hidden for mobile view. These classes will be able to trigger the same.

Classe Names:
`.p-col-hide`
`.p-sm-hide` - For small devices
`.p-md-hide` - For medium devices
`.p-lg-hide` - For large devices
`.p-xl-hide` - For very large devices

### CODE REVIEW

**Comment by jotae1e** [comment]
What about this?

**Comment by mikaelboff** [comment]
Could you please merge this feature? It's very necessary to our business

**Comment by mikaelboff** [comment]
Do you guys have any plan of when you'll merge this? @cagataycivici @onursenture

**Comment by mikaelboff** [comment]
@mertsincan can you help us?

**Comment by mikaelboff** [comment]
+1

**Comment by mertsincan** [comment]
Hi @praveenkumar-outlook,

p-${breakpoint}-hide class is OK for me. But, why don't you add display: block? Users can use inline element. I think users can made their own styles using @media and our breakpoint variables.

Best Regards,

**Comment by jotae1e** [comment]
> Hi @praveenkumar-outlook,
> 
> Why don't you add display: block? Users can use inline element. I think users can made their own styles using @media and our breakpoint variables.
> 
> Best Regards,

Can you post an example of this?

Thanks in advance

**Comment by mikeandtherest** [comment]
@mertsincan @cagataycivici  Hey. Since such classes are always handy when trying to accommodate for various screen resolutions, I don't get why can't the lib provide them out of the box? I know that we can manually achieve that on our projects by leveraging the existing bp variables, but still.

At least let us know if there are any plans down the road to add them.

**Pull request closed without merging**
