### PR TITLE
Allow for overriding breakpoints

### PR DESCRIPTION
**Pull request by danini-the-panini**
1. Use the breakpoint variables in the breakpoint map to allow overriding existing breakpoint values
2. Add `!default` to the breakpoints map to allow for adding/removing breakpoints

### CODE REVIEW

**Comment by cagataycivici** [comment]
V3 has them as !default.

**Comment by danini-the-panini** [comment]
@cagataycivici this is only partially true. While the individual breakpoint variables are !default, the map is not, and does not use the individual breakpoints, which makes it impossible to properly override them.

Please re-open this.

**Comment by melloware** [comment]
@cagataycivici I agree with @danini-the-panini assessment.

**Comment by gpolcode** [comment]
@cagataycivici we need this aswell to add additional breakpoints. can you please reopen this?

**Review by jfitzsimmons2 — COMMENTED** [review]
This would be super helpful to merge in, it would allow for greater flexibility in breakpoints and creating new breakpoint classes.

**Comment by melloware** [comment]
Can someone open a new ticket and reference this ticket since this on is closed.

**Comment by melloware** [comment]
I would open a new ticket so it gets visibility and explain why `default` was not enough to fix this.  Or submit a PR as well

**Comment by danini-the-panini** [comment]
I've mentioned this PR in the following issues, which are both open:
https://github.com/primefaces/primeflex/issues/52
https://github.com/primefaces/primeflex/issues/47

**Pull request closed without merging**
