### PR TITLE
responsiveness for .col & .col-fixed

### PR DESCRIPTION
**Pull request by jiangyh1024**
please have a check to see if it is OK

### CODE REVIEW

**Comment by ProfEibe** [comment]
Please include this pull-request!

**Review by melloware — APPROVED** [review]

**Comment by rubjo** [comment]
🤔 I think there might have to be some `width: unset;`s in there for this to work in practice.

**Comment by melloware** [comment]
Looks like this is added in 3.2.0 with ticket #82. Can you verify and close if so.

**Comment by mertsincan** [comment]
Oops! So sorry, @jiangyh1024 :( I didn't see your PR! 

Thanks a lot for your PR!
Best Regards,

**Pull request closed without merging**
